apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xoffice-avatars-pvc
  namespace: xoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
